name: Run Selenium C# Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.403'  # Specify the version of .NET you are using

      - name: Restore dependencies
        run: dotnet restore ./AutomationExercise.SeleniumNUnit/AutomationExercise.SeleniumNUnit.csproj

      - name: Build project
        run: dotnet build ./AutomationExercise.SeleniumNUnit/AutomationExercise.SeleniumNUnit.csproj

      - name: Run tests
        run: dotnet test ./AutomationExercise.SeleniumNUnit/AutomationExercise.SeleniumNUnit.csproj

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestReport
          path: |
            AutomationExercise.SeleniumNUnit/Screenshots/
            AutomationExercise.SeleniumNUnit/Reports/ExtentReport.html

